In [1]:
import numpy as np

In [55]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [56]:
type(arr)

numpy.ndarray

In [57]:
arr.ndim #n-dimensional - has only rows

1

In [27]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr1.ndim

2

In [34]:
mat = np.matrix([1,2,3,4]) #numpy.matrix -- Matrix is a specialised 2D array
mat

matrix([[1, 2, 3, 4]])

In [33]:
type(mat)

numpy.matrix

In [36]:
arr1 = np.array([[[1,2],[3,4],[5,6]]])
arr1

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [37]:
arr1.ndim

3

In [38]:
#ways to create array
#1 using np.array
#2 using np.asarray

l = [1,2,3,4]
l

[1, 2, 3, 4]

In [39]:
type(l)

list

In [41]:
arr2 = np.asarray(l)
arr2

array([1, 2, 3, 4])

In [42]:
type(arr2)

numpy.ndarray

In [43]:
#3. asanyarray

arr3 = np.asanyarray([1,2,3,4])
arr3

array([1, 2, 3, 4])

In [44]:
type(arr3)

numpy.ndarray

In [45]:
arr3.size # no.of elements in a array

4

In [46]:
arr3.shape

(4,)

In [47]:
#can tuple be converted into array ? - yes
tup = ([1,2,3],[4,6,8])
tup

([1, 2, 3], [4, 6, 8])

In [48]:
type(tup)

tuple

In [50]:
arr4 = np.array(tup)
arr4

array([[1, 2, 3],
       [4, 6, 8]])

In [58]:
arr[0]

np.int64(1)

In [62]:
arr[0] = 100 #array is mutable
arr

array([100,   2,   3,   4])

In [63]:
a = arr # shallow copy - it will points the same memory location , if you alter in one array ill reflect on other as well 
a

array([100,   2,   3,   4])

In [64]:
arr

array([100,   2,   3,   4])

In [65]:
a[0]

np.int64(100)

In [69]:
a[0] = 10 # lets say i am updating oth index to 10 from 100, so as per the shalllow copy it should reflect in arr array also.

In [70]:
a

array([10,  2,  3,  4])

In [71]:
arr

array([10,  2,  3,  4])

In [72]:
## deep copy - 

In [77]:
a1 = a.copy() ## deepcopy 
a1

array([10,  2,  3,  4])

In [78]:
a

array([10,  2,  3,  4])

In [80]:
a1[0] = 20 # altered a1 oth index to 20 from 10, so deep copy will not update the original value in the other array
a1

array([20,  2,  3,  4])

In [81]:
a

array([10,  2,  3,  4])

In [89]:
#multiple way to generate array
arr1 = np.fromfunction(lambda x,y: y == x**2 ,(3,3))
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [90]:
arr1 = np.fromfunction(lambda x,y: x == y ,(3,3))
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [91]:
arr1.ndim

2

In [92]:
arr1.shape

(3, 3)

In [94]:
arr1 = np.fromfunction(lambda x,y: x == x * y ,(3,3))
arr1

array([[ True,  True,  True],
       [False,  True, False],
       [False,  True, False]])

In [101]:
for i in range(5):
    print(i)

0
1
2
3
4


In [106]:
arr = [i for i in range(5)]
arr

[0, 1, 2, 3, 4]

In [107]:
type(arr)

list

In [108]:
list([i for i in range(5)])

[0, 1, 2, 3, 4]

In [114]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [120]:
np.linspace(1,100,9)

array([  1.   ,  13.375,  25.75 ,  38.125,  50.5  ,  62.875,  75.25 ,
        87.625, 100.   ])

In [122]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [126]:
z1 = np.zeros(3, dtype = int)
z1

array([0, 0, 0])

In [127]:
z1.ndim

1

In [129]:
z2 = np.zeros((2,3), dtype = int)
z2

array([[0, 0, 0],
       [0, 0, 0]])

In [131]:
z3 = np.ones((2,3), dtype = int)
z3

array([[1, 1, 1],
       [1, 1, 1]])

In [134]:
arr1 = np.array([[2,2,2],[2,2,2]])
arr1

array([[2, 2, 2],
       [2, 2, 2]])

In [141]:
arr1 = np.zeros((1,3,4),dtype = int)
arr1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [149]:
sum1 = arr1+5 # sum
sum1

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [151]:
sub = arr1-6 #subtraction
sub

array([[[-6, -6, -6, -6],
        [-6, -6, -6, -6],
        [-6, -6, -6, -6]]])

In [152]:
sub * sum1 # multiplicaion

array([[[-30, -30, -30, -30],
        [-30, -30, -30, -30],
        [-30, -30, -30, -30]]])

In [156]:
np.eye(3, dtype = int) # identity matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [162]:
np.empty((3,4),dtype = int) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [165]:
#random module
import random as rd

rd.choice((1,2,3,4))

1

In [167]:
rd.randrange(1,10)

5

In [168]:
rd.choice("shivanand")

'n'

In [171]:
rd.random() # random number gives between 0 and 1

0.2727361548413364

In [172]:
l = [1,2,3,4]
l

[1, 2, 3, 4]

In [175]:
rd.shuffle(l)
l

[1, 4, 2, 3]

In [181]:
import numpy as np
np.random.random_sample()

0.5877888691994572

In [185]:
np.random.random_sample((5,))

array([0.48007471, 0.69794574, 0.67348414, 0.38818797, 0.53610899])

In [188]:
np.random.rand(1)

array([0.05959888])

In [193]:
np.random.randn(2,3) #Return a sample (or samples) from the "standard normal" distribution.

array([[-2.87463347,  1.29863111,  0.38216912],
       [-0.55907887,  0.9749487 ,  1.24711642]])

In [196]:
np.random.randint(1,5, size = (3,4))

array([[1, 4, 4, 3],
       [2, 4, 1, 1],
       [3, 3, 1, 3]])

In [197]:
arr1 = np.random.randint(1,5, size = (3,4))
arr1

array([[4, 2, 2, 3],
       [2, 2, 4, 4],
       [3, 1, 2, 2]])

In [199]:
arr1.shape

(3, 4)

In [202]:
arr1.reshape(2,6)

array([[4, 2, 2, 3, 2, 2],
       [4, 4, 3, 1, 2, 2]])

In [203]:
arr1.reshape(2,-1) # if you donot know the row*colm value

array([[4, 2, 2, 3, 2, 2],
       [4, 4, 3, 1, 2, 2]])

In [204]:
arr1.reshape(-1,4)

array([[4, 2, 2, 3],
       [2, 2, 4, 4],
       [3, 1, 2, 2]])

In [205]:
arr1.reshape(-1,4).base

array([[4, 2, 2, 3],
       [2, 2, 4, 4],
       [3, 1, 2, 2]])

In [206]:
arr1.reshape(1,2,3,2)

array([[[[4, 2],
         [2, 3],
         [2, 2]],

        [[4, 4],
         [3, 1],
         [2, 2]]]])

In [213]:
arr2 = np.random.randint(1,5, size = (3,4))
arr2

array([[4, 2, 2, 2],
       [4, 2, 4, 4],
       [1, 4, 4, 4]])

In [217]:
arr2>=3

array([[ True, False, False, False],
       [ True, False,  True,  True],
       [False,  True,  True,  True]])

In [218]:
arr2

array([[4, 2, 2, 2],
       [4, 2, 4, 4],
       [1, 4, 4, 4]])

In [227]:
arr3 = np.random.randint(1,5, size = (8,9))
arr3

array([[3, 4, 1, 3, 4, 3, 4, 2, 2],
       [2, 1, 1, 4, 4, 4, 2, 2, 1],
       [1, 2, 4, 3, 4, 2, 3, 3, 2],
       [2, 4, 1, 1, 3, 3, 2, 4, 2],
       [4, 3, 2, 3, 3, 1, 3, 2, 1],
       [2, 4, 2, 1, 4, 2, 1, 3, 2],
       [1, 1, 1, 2, 4, 2, 2, 1, 1],
       [4, 1, 1, 1, 1, 1, 4, 3, 3]])

In [230]:
arr3[0][8] ## accesing the element using index

np.int64(2)

In [236]:
# from 0th row to 2rd row
arr3[0:3]

array([[3, 4, 1, 3, 4, 3, 4, 2, 2],
       [2, 1, 1, 4, 4, 4, 2, 2, 1],
       [1, 2, 4, 3, 4, 2, 3, 3, 2]])

In [235]:
# from 0th row to 2rd row  and 0th and 2nd column
arr3[0:3,[0,2]]

array([[3, 1],
       [2, 1],
       [1, 4]])

In [238]:
# 0th row to 2nd row and (2nd column and 3rd colmn) 
arr3[0:3,[1,2]]

array([[4, 1],
       [1, 1],
       [2, 4]])

In [255]:
#mathematical operations :
import random
import numpy as np

In [265]:
arr1 = np.random.randint(1,2, size = (3,3))
arr2 = np.random.randint(1,2, size = (3,3))


In [273]:
arr1, arr2

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]))

In [274]:
arr1+arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [275]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [276]:
arr1*arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [277]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [271]:
arr1%arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [278]:
arr1 @ arr2 # matrix multiplication is a special type of multiplication.

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [290]:
#Transpose of a matrix
a = np.array([1,2,3,4])

In [291]:
a

array([1, 2, 3, 4])

In [294]:
a.size #4
a.shape # (4,)
a.ndim #1

1

In [289]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [295]:
#Transpose of a matrix is valid for 2D 

a = np.array([[1,2,3,4]])
a

array([[1, 2, 3, 4]])

In [296]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [302]:
arr1 = np.random.randint(1,5, size = (3,4))
arr1

array([[4, 1, 2, 4],
       [2, 1, 3, 4],
       [2, 1, 1, 4]])

In [304]:
arr1.T # Transpose of a array will give you the rows into columns and columns into rows

array([[4, 2, 2],
       [1, 1, 1],
       [2, 3, 1],
       [4, 4, 4]])

In [306]:
arr1 = np.random.randint(1,3, size = (3,3))
arr2 = np.random.randint(1,3, size = (3,3))

In [307]:
arr1, arr2

(array([[1, 1, 2],
        [2, 1, 1],
        [1, 2, 1]]),
 array([[1, 1, 1],
        [1, 2, 2],
        [1, 1, 2]]))

In [316]:
arr1.flatten() #Return a copy of the array collapsed into one dimension.

array([1, 1, 2, 2, 1, 1, 1, 2, 1])

In [318]:
# expand the dimension
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [327]:
np.expand_dims(arr1,axis = 1) #Expand the shape of an array.

array([[1],
       [2],
       [3],
       [4]])

In [328]:
np.expand_dims(arr1,axis = 1).ndim

2

In [332]:
arr = np.zeros((2,2))
arr

array([[0., 0.],
       [0., 0.]])

In [334]:
np.expand_dims(arr,axis = 1).ndim

3

In [341]:
a = np.array([[1],[2],[3]])
a

array([[1],
       [2],
       [3]])

In [344]:
a.ndim

2

In [345]:
np.squeeze(a) #Remove axes of length one from `a`.

array([1, 2, 3])

In [346]:
a

array([[1],
       [2],
       [3]])

In [347]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [348]:
arr1

array([1, 2, 3, 4])

In [351]:
np.repeat(arr1,2, axis = 0)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [356]:
arr10 = np.random.randint(2,5,(3,4))

In [357]:
arr10

array([[3, 4, 4, 4],
       [4, 3, 2, 2],
       [2, 4, 4, 4]])

In [358]:
np.repeat(arr10,2)

array([3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 4])

In [361]:
np.repeat(arr10,2, axis = 0)

array([[3, 4, 4, 4],
       [3, 4, 4, 4],
       [4, 3, 2, 2],
       [4, 3, 2, 2],
       [2, 4, 4, 4],
       [2, 4, 4, 4]])

In [362]:
a

array([[1],
       [2],
       [3]])

In [365]:
np.roll(a,-1)  #Roll array elements along a given axis.

array([[2],
       [3],
       [1]])

In [366]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [367]:
np.roll(a,-1) #single value

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 1]])

In [368]:
np.roll(a,2) #paired value

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [369]:
np.roll(a,2, axis = 0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [371]:
#Mathematical oprations

arr1, arr2

(array([1, 2, 3, 4]),
 array([[1, 1, 1],
        [1, 2, 2],
        [1, 1, 2]]))

In [372]:
arr1+arr2 # gives error as shapes are not equal

ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

In [373]:
~arr2

array([[-2, -2, -2],
       [-2, -3, -3],
       [-2, -2, -3]])

In [377]:
#operations on numpy string array

arr = np.array(["pwskills",'ds'])
arr

array(['pwskills', 'ds'], dtype='<U8')

In [378]:
np.char.capitalize(arr) 
#Return a copy of ``a`` with only the first character of each element capitalized.

array(['Pwskills', 'Ds'], dtype='<U8')

In [380]:
np.char.upper(arr) #Return an array with the elements converted to uppercase.


array(['PWSKILLS', 'DS'], dtype='<U8')

In [384]:
#Mathematical functions

In [385]:
arr1 = np.random.randint(2,5,(3,4))
arr1

array([[3, 3, 2, 2],
       [4, 4, 4, 4],
       [3, 3, 3, 4]])

In [386]:
np.sin(arr1)

array([[ 0.14112001,  0.14112001,  0.90929743,  0.90929743],
       [-0.7568025 , -0.7568025 , -0.7568025 , -0.7568025 ],
       [ 0.14112001,  0.14112001,  0.14112001, -0.7568025 ]])

In [387]:
np.cos(arr1)

array([[-0.9899925 , -0.9899925 , -0.41614684, -0.41614684],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.9899925 , -0.9899925 , -0.9899925 , -0.65364362]])

In [388]:
np.tan(arr1)

array([[-0.14254654, -0.14254654, -2.18503986, -2.18503986],
       [ 1.15782128,  1.15782128,  1.15782128,  1.15782128],
       [-0.14254654, -0.14254654, -0.14254654,  1.15782128]])

In [389]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.30103   ],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.47712125, 0.47712125, 0.47712125, 0.60205999]])

In [390]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 ,  7.3890561 ],
       [54.59815003, 54.59815003, 54.59815003, 54.59815003],
       [20.08553692, 20.08553692, 20.08553692, 54.59815003]])

In [391]:
np.min(arr1)

np.int64(2)

In [392]:
np.mean(arr1)

np.float64(3.25)

In [393]:
np.std(arr1)

np.float64(0.7216878364870323)

In [399]:
arr1 = np.random.randint(2,5,(3,4))
arr2 = np.random.randint(2,5,(3,4))
arr1,arr2

(array([[2, 4, 4, 4],
        [4, 4, 4, 4],
        [2, 3, 2, 4]]),
 array([[2, 3, 4, 2],
        [4, 3, 4, 4],
        [2, 4, 2, 2]]))

In [396]:
arr1 * arr2

array([[ 4,  4,  6, 12],
       [12, 12,  8,  8],
       [12,  8,  4,  6]])

In [398]:
np.multiply(arr1,arr2)

array([[ 4,  4,  6, 12],
       [12, 12,  8,  8],
       [12,  8,  4,  6]])

In [400]:
np.multiply(arr1,2)

array([[4, 8, 8, 8],
       [8, 8, 8, 8],
       [4, 6, 4, 8]])

In [401]:
np.sqrt(arr1)

array([[1.41421356, 2.        , 2.        , 2.        ],
       [2.        , 2.        , 2.        , 2.        ],
       [1.41421356, 1.73205081, 1.41421356, 2.        ]])

In [402]:
np.square(arr1)

array([[ 4, 16, 16, 16],
       [16, 16, 16, 16],
       [ 4,  9,  4, 16]])

In [403]:
#sorting and searching in numpy
r = np.array([5,8,3,2])
r

array([5, 8, 3, 2])

In [404]:
np.sort(r)

array([2, 3, 5, 8])

In [409]:
f = np.searchsorted(r,4) #Find indices where elements should be inserted to maintain order.
f

np.int64(4)

In [412]:
np.count_nonzero(r)

4

In [413]:
import numpy.matlib as nm

In [415]:
nm.zeros(5, dtype = int)

matrix([[0, 0, 0, 0, 0]])

In [419]:
#in matrix you cannot devide by another matrix 
arr1 = np.random.randint(1,2,(3,3))
arr1


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [420]:
np.linalg.det(arr1)

np.float64(0.0)

In [431]:
#Compute the inverse of a matrix.
import numpy as np
from numpy.linalg import inv, det

#create 2x2 matrix that is not singular
my_matrix = np.array([[1., 7.], [4., 2.]])


#calculate inverse of matrix
print(inv(my_matrix))


[[-0.07692308  0.26923077]
 [ 0.15384615 -0.03846154]]
