<a href="https://colab.research.google.com/github/Shivauppe/NumPy/blob/main/NumPy_Lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [15]:
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
x1[0]

5

In [17]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [13]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
x1[1::2]

array([0, 3, 9])

In [19]:
x1.size

6

In [21]:
x1.reshape(2,3)

array([[5, 0, 3],
       [3, 7, 9]])

In [23]:
x1.reshape(2,3).shape

(2, 3)

In [26]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[::2]  # every other element


array([0, 2, 4, 6, 8])

In [28]:
x[1::2]  # every other element, starting at index 1


array([1, 3, 5, 7, 9])

In [29]:
x[::-1]  # all elements, reversed


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2]  # reversed every other from index 5


array([5, 3, 1])

In [31]:
x2


array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [32]:
x2[:2, :3]  # two rows, three columns


array([[3, 5, 2],
       [7, 6, 8]])

In [33]:
x2.ndim

2